"""Initial migration - email models

Revision ID: 52360869d946
Revises: 
Create Date: 2025-07-21 22:27:14.007822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52360869d946'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_rate_limits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_rate_limits_email'), 'email_rate_limits', ['email'], unique=False)
    op.create_table('email_subscribers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('confirmation_code', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_subscribers_confirmation_code'), 'email_subscribers', ['confirmation_code'], unique=True)
    op.create_index(op.f('ix_email_subscribers_email'), 'email_subscribers', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_subscribers_email'), table_name='email_subscribers')
    op.drop_index(op.f('ix_email_subscribers_confirmation_code'), table_name='email_subscribers')
    op.drop_table('email_subscribers')
    op.drop_index(op.f('ix_email_rate_limits_email'), table_name='email_rate_limits')
    op.drop_table('email_rate_limits')
    # ### end Alembic commands ###
